/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\models\freeRoamStage\model.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh.geometry} material={materials.base_material} position={[0, 1.265, 0]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={15} />
    </group>
  )
}

useGLTF.preload('/model.gltf')
