/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/stage/model.gltf --output ./src/components/Model.js 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.eiffel.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.arc20.geometry} material={materials.Material} />
      <mesh geometry={nodes.pyramid.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes['4lane'].geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.footing_02.geometry} material={materials['Material.037']} />
      <mesh geometry={nodes.tmplj4peh38.geometry} material={materials.material_0} />
      <mesh geometry={nodes.tmpxoxwiefl.geometry} material={materials['Material.005']} />
    </group>
  )
}

useGLTF.preload('/model.gltf')
