/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/male/model.gltf --output ./src/components/Model.js 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/model.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="newCharacter" position={[-0.004, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.03}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Mesh_0002" geometry={nodes.Mesh_0002.geometry} material={materials['Material_0.003']} skeleton={nodes.Mesh_0002.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model.gltf')
