/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/roam/model.gltf --output ./src/components/Model.js 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Roam(props) {
  const { nodes, materials } = useGLTF('./models/roam/model.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bakery.geometry} material={materials.base_material} position={[0, 3.437, -9.575]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={15} />
      <mesh geometry={nodes.footing_02.geometry} material={materials['Material.037']} position={[0.068, 0.165, -0.085]} scale={4.923} />
    </group>
  )
}

useGLTF.preload('./models/roam/model.gltf')
