/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Stage(props) {
  const { nodes, materials } = useGLTF('./models/stage/model.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.eiffel.geometry} material={materials['Material.002']} />
      <mesh geometry={nodes.arc20.geometry} material={materials.Material} />
      <mesh geometry={nodes.pyramid.geometry} material={materials['Material.001']} />
      <mesh geometry={nodes['4lane'].geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.footing_02.geometry} material={materials['Material.037']} />
      <mesh geometry={nodes.tmplj4peh38.geometry} material={materials.material_0} />
      <mesh geometry={nodes.tmpxoxwiefl.geometry} material={materials['Material.005']} />
    </group>
  )
}

useGLTF.preload('./models/stage/model.gltf')