/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/baker/model.gltf --output ./src/Model.js 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/model.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Baker" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="tmp89gy3jzx" geometry={nodes.tmp89gy3jzx.geometry} material={materials['Material.004']} skeleton={nodes.tmp89gy3jzx.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/model.gltf')
