/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/models/stage/model.gltf --output ./src/Model.js 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Stage(props) {
  const { nodes, materials } = useGLTF('./models/stage/model.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.arc20.geometry} material={materials.Material} />
      <mesh geometry={nodes.footing_02.geometry} material={materials['Material.037']} />
      <mesh geometry={nodes.tmpxoxwiefl.geometry} material={materials['Material.005']} />
      <mesh geometry={nodes.tmpjxuqkcug.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes.tmpvk8dpl2l001.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.tmprqvlyywb002.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.tmpkmup53ly002.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.tmprqvlyywb003.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.tmpjxuqkcug002.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes.tmpvk8dpl2l002.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.tmprqvlyywb004.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.tmpkmup53ly003.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.tmpjxuqkcug003.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes.tmpvk8dpl2l003.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.tmpjxuqkcug004.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes.tmprqvlyywb005.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.tmpkmup53ly004.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.tmpvk8dpl2l004.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.tmpjxuqkcug005.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes.tmpvk8dpl2l005.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.tmpjxuqkcug006.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes.tmpvk8dpl2l006.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.tmpvk8dpl2l007.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.tmpvk8dpl2l008.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.tmpjxuqkcug007.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes.tmprqvlyywb006.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.tmprqvlyywb007.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.tmpvk8dpl2l009.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.tmpvk8dpl2l010.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.tmpkmup53ly005.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.tmprqvlyywb008.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.tmprqvlyywb009.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.tmpjxuqkcug008.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes.tmpjxuqkcug009.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes.tmpjxuqkcug010.geometry} material={materials['Material.014']} />
      <mesh geometry={nodes.tmpkmup53ly006.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.tmphaj03ybh032.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.tmphaj03ybh059.geometry} material={materials['Material.012']} />
      <mesh geometry={nodes.tmpvk8dpl2l019.geometry} material={materials['Material.010']} />
      <mesh geometry={nodes.tmprqvlyywb013.geometry} material={materials['Material.011']} />
      <mesh geometry={nodes.tmpkmup53ly010.geometry} material={materials['Material.006']} />
      <mesh geometry={nodes.tmpgp_truo6.geometry} material={materials['Material.016']} />
      <mesh geometry={nodes.map_2osm_roofs.geometry} material={materials['Material.017']} />
      <mesh geometry={nodes.Terrain001.geometry} material={materials['overlay.001']} />
      <mesh geometry={nodes.Terrain001_envelope.geometry} material={nodes.Terrain001_envelope.material} />
      <mesh geometry={nodes.map_2osm_buildings_1.geometry} material={materials.wall} />
      <mesh geometry={nodes.map_2osm_buildings_2.geometry} material={materials['000000']} />
      <mesh geometry={nodes.map_2osm_buildings_3.geometry} material={materials.cac6ba} />
      <mesh geometry={nodes.map_2osm_buildings_4.geometry} material={materials.red} />
      <mesh geometry={nodes.map_2osm_buildings_5.geometry} material={materials['808080']} />
      <mesh geometry={nodes.map_2osm_buildings_6.geometry} material={materials['2a2e52']} />
      <mesh geometry={nodes.map_2osm_buildings_7.geometry} material={materials.palevioletred} />
      <mesh geometry={nodes.map_2osm_buildings_8.geometry} material={materials.darkgrey} />
      <mesh geometry={nodes.map_2osm_buildings_9.geometry} material={materials.beige} />
      <mesh geometry={nodes.map_2osm_buildings_10.geometry} material={materials.gray} />
      <mesh geometry={nodes.map_2osm_buildings_11.geometry} material={materials.black} />
      <mesh geometry={nodes.map_2osm_buildings_12.geometry} material={materials.d0d0d0} />
      <mesh geometry={nodes.map_2osm_buildings_13.geometry} material={materials['828282']} />
      <mesh geometry={nodes.map_2osm_buildings_14.geometry} material={materials['8df0b8']} />
      <mesh geometry={nodes.map_2osm_buildings_15.geometry} material={materials.white} />
      <mesh geometry={nodes.map_2osm_buildings_16.geometry} material={materials.brown} />
      <mesh geometry={nodes.map_2osm_buildings_17.geometry} material={materials['4f4f4f']} />
      <mesh geometry={nodes.map_2osm_buildings_18.geometry} material={materials.b3b2b8} />
      <mesh geometry={nodes.map_2osm_buildings_19.geometry} material={materials.c0ede7} />
      <mesh geometry={nodes.map_2osm_buildings_20.geometry} material={materials['595b70']} />
      <mesh geometry={nodes.map_2osm_buildings_21.geometry} material={materials.eecfaf} />
      <mesh geometry={nodes.map_2osm_buildings_22.geometry} material={materials.d37e3e} />
      <mesh geometry={nodes.map_2osm_buildings_23.geometry} material={materials.f2ebd8} />
      <mesh geometry={nodes.map_2osm_buildings_24.geometry} material={materials.aaaaaa} />
    </group>
  )
}

useGLTF.preload('./models/stage/model.gltf')
